doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 120
uses:
    - django
    - celery
autodetect: yes
ignore-paths:
    - docs
    - mypackage/vendor
ignore-patterns:
    - ^source/conf.py$

